import React, { useState } from 'react';
import { 
  X, 
  ChevronRight, 
  ChevronLeft, 
  Zap, 
  TrendingUp, 
  ShieldCheck, 
  Bot, 
  Sparkles, 
  Layers, 
  CheckCircle2,
  ArrowDownUp
} from 'lucide-react';

interface NewUserTourModalProps {
  isOpen: boolean;
  onClose: () => void;
  userAddress?: string | null;
}

export const NewUserTourModal: React.FC<NewUserTourModalProps> = ({
  isOpen,
  onClose,
  userAddress,
}) => {
  const [currentStep, setCurrentStep] = useState<number>(0);

  if (!isOpen) return null;

  const steps = [
    {
      badge: 'Step 1 of 5 • Architecture',
      title: 'Automated Yield on Stellar & Soroban',
      description:
        'Lumex is a non-custodial yield optimization protocol. Instead of letting your XLM, USDC, or AQUA sit idle in your wallet, our smart contracts put your assets to work directly in native Stellar DEX AMM liquidity pools.',
      icon: Layers,
      color: '#00E599',
      image: '/images/hero-vault-3d.png',
      features: [
        'Built directly on Stellar Protocol 20+ and Soroban Rust smart contracts.',
        'Zero gas overhead: typical transactions cost less than $0.00001.',
        'Deposit with as little as 10 XLM without losing profits to gas fees.',
      ],
    },
    {
      badge: 'Step 2 of 5 • Real Yield',
      title: 'Where Does the Yield Come From?',
      description:
        'Zero gimmicks or fake inflation. Every single swap executed on the Stellar DEX charges a 0.30% trading fee. Lumex vault depositors earn 100% of these fees proportional to their pool share.',
      icon: TrendingUp,
      color: '#3B82F6',
      image: '/images/yield-growth-3d.png',
      features: [
        'DEX volume generated by real-world remittance and global trading.',
        'Shares appreciate continuously as trading fees accumulate in the pool.',
        'Dynamic APY rates ranging from 12% to 31.8% based on live pool volume.',
      ],
    },
    {
      badge: 'Step 3 of 5 • Token Exchange',
      title: 'Soroban Constant-Product Token Swap',
      description:
        'Traders and users can swap assets directly against our Soroban smart contract liquidity pools. Every trade charges a 0.30% fee that feeds directly into the vault to generate real staking returns.',
      icon: ArrowDownUp,
      color: '#00C2FF',
      image: '/images/hero-vault-3d.png',
      features: [
        'Instant liquidity swaps between XLM, USDC, and AQUA.',
        '0.30% swap fee routes directly into the vault pool for depositors.',
        'Enables a fully closed-loop decentralized exchange economy on Stellar.',
      ],
    },
    {
      badge: 'Step 4 of 5 • Auto-Compounding',
      title: '15-Minute Decentralized Keeper Harvesting',
      description:
        'Normally, compounding requires manual claiming and gas fees. Lumex features open keeper bots that harvest and reinvest trading fees every 15 minutes, incentivized by a 1% bounty.',
      icon: Bot,
      color: '#A855F7',
      image: '/images/keeper-bot-3d.png',
      features: [
        'Autonomous compound cycles running on the Stellar network.',
        'Anyone can trigger compound cycles and claim the 1% keeper reward.',
        'Continuous compound curves maximize APY over time.',
      ],
    },
    {
      badge: 'Step 5 of 5 • Non-Custodial Safety',
      title: '100% Non-Custodial & Instant Emergency Exit',
      description:
        'You always retain full cryptographic ownership of your deposited assets. There are no lockup periods or withdrawal restrictions. Withdraw anytime or use the 1-Click Instant Emergency Exit.',
      icon: ShieldCheck,
      color: '#00E599',
      image: '/images/emergency-shield-3d.png',
      features: [
        'Instant Emergency Exit burns vault shares and returns 100% principal.',
        'Direct cryptographic settlement verified on Stellar testnet ledgers.',
        'Transparent on-chain telemetry and verifiable transaction proofs.',
      ],
    },
  ];


  const step = steps[currentStep];
  const StepIcon = step.icon;

  const handleNext = () => {
    if (currentStep < steps.length - 1) {
      setCurrentStep(currentStep + 1);
    } else {
      handleComplete();
    }
  };

  const handleBack = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
    }
  };

  const handleComplete = () => {
    if (userAddress) {
      try {
        localStorage.setItem(`lumex_tour_completed_${userAddress}`, 'true');
      } catch (e) {}
    }
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-2xl rounded-2xl border border-white/[0.12] bg-[#0A0D14] p-6 sm:p-8 shadow-2xl shadow-[#00E599]/10">
        {/* Close Button */}
        <button
          onClick={handleComplete}
          className="absolute right-4 top-4 rounded-xl p-2 text-slate-400 hover:bg-white/[0.06] hover:text-white transition-colors"
        >
          <X className="h-5 w-5" />
        </button>

        {/* Progress Indicators */}
        <div className="flex items-center gap-2 mb-6">
          {steps.map((_, idx) => (
            <div
              key={idx}
              className={`h-1.5 flex-1 rounded-full transition-all duration-300 ${
                idx === currentStep
                  ? 'bg-[#00E599] shadow-sm shadow-[#00E599]/50'
                  : idx < currentStep
                  ? 'bg-emerald-800'
                  : 'bg-white/[0.08]'
              }`}
            />
          ))}
        </div>

        {/* Step Header */}
        <div className="flex items-center gap-3 mb-4">
          <div
            className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/[0.1] bg-white/[0.04]"
            style={{ color: step.color }}
          >
            <StepIcon className="h-5 w-5" />
          </div>
          <div>
            <span className="text-[11px] font-semibold uppercase tracking-wider text-[#00E599]">
              {step.badge}
            </span>
            <h3 className="text-xl sm:text-2xl font-bold text-white leading-tight">
              {step.title}
            </h3>
          </div>
        </div>

        {/* Visual Banner */}
        <div className="relative mb-6 h-40 sm:h-48 w-full overflow-hidden rounded-xl border border-white/[0.08] bg-[#05070B] flex items-center justify-center">
          <img
            src={step.image}
            alt={step.title}
            className="h-full w-full object-cover opacity-90 transition-transform duration-500 hover:scale-105"
            onError={(e) => {
              (e.target as HTMLElement).style.display = 'none';
            }}
          />
          <div className="absolute inset-0 bg-gradient-to-t from-[#0A0D14] via-transparent to-transparent" />
        </div>

        {/* Description */}
        <p className="text-sm sm:text-base text-slate-300 leading-relaxed mb-6">
          {step.description}
        </p>

        {/* Feature List */}
        <div className="space-y-2.5 mb-8 rounded-xl border border-white/[0.06] bg-white/[0.02] p-4">
          {step.features.map((feat, i) => (
            <div key={i} className="flex items-start gap-2.5 text-xs sm:text-sm text-slate-300">
              <CheckCircle2 className="h-4 w-4 text-[#00E599] shrink-0 mt-0.5" />
              <span>{feat}</span>
            </div>
          ))}
        </div>

        {/* Navigation Buttons */}
        <div className="flex items-center justify-between gap-4 pt-4 border-t border-white/[0.08]">
          <button
            onClick={handleBack}
            disabled={currentStep === 0}
            className={`flex items-center gap-1.5 px-4 py-2.5 rounded-xl border border-white/[0.08] text-xs font-semibold transition-all ${
              currentStep === 0
                ? 'opacity-30 cursor-not-allowed text-slate-500'
                : 'text-slate-300 hover:bg-white/[0.06] hover:text-white'
            }`}
          >
            <ChevronLeft className="h-4 w-4" />
            <span>Back</span>
          </button>

          <div className="flex items-center gap-3">
            <button
              onClick={handleComplete}
              className="text-xs text-slate-400 hover:text-white px-3 py-2 transition-colors"
            >
              Skip Tour
            </button>
            <button
              onClick={handleNext}
              className="flex items-center gap-2 px-6 py-2.5 rounded-xl bg-gradient-to-r from-[#00E599] to-emerald-400 text-xs font-bold text-slate-950 hover:brightness-110 active:scale-95 shadow-lg shadow-[#00E599]/20 transition-all"
            >
              <span>{currentStep === steps.length - 1 ? 'Start Earning Yield' : 'Next Step'}</span>
              {currentStep === steps.length - 1 ? (
                <Sparkles className="h-4 w-4" />
              ) : (
                <ChevronRight className="h-4 w-4" />
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
