/**
 * ==============================================================================
 * Lumex Protocol — Verifiable On-Chain User Interactions Proof Component
 * ==============================================================================
 * 
 * Renders real on-chain transaction proofs generated by genuine testnet wallets:
 * - Direct links to StellarExpert block explorer verifying tx hash, ledger, and signatures.
 * - Action-based filtering (Deposit, Withdraw, Auto-Compound, Emergency-Exit).
 * - Real-time client search across Public Key, Tx Hash, and Pool ID.
 * - Merges static verifiable genesis proofs with live active session transactions.
 */

import React, { useState } from 'react';
import { 
  ShieldCheck, 
  ExternalLink, 
  Search, 
  Layers, 
  Activity, 
  Sparkles, 
  ArrowUpRight, 
  ArrowDownRight 
} from 'lucide-react';
import { OnChainTransactionProof } from '../types';
import { STELLAR_CONFIG } from '../config/stellar';
import proofData from '../data/userInteractionsProof.json';

export const INITIAL_ONCHAIN_PROOFS: OnChainTransactionProof[] = proofData as OnChainTransactionProof[];

interface ProofOfInteractionsProps {
  txHistory: OnChainTransactionProof[];
}

export const ProofOfInteractions: React.FC<ProofOfInteractionsProps> = ({ txHistory }) => {
  const [filterAction, setFilterAction] = useState<string>('All');
  const [searchTerm, setSearchTerm] = useState<string>('');

  // Merge verified on-chain batch proofs with any live session transactions
  const allProofs = [...txHistory, ...INITIAL_ONCHAIN_PROOFS];

  const filteredProofs = allProofs.filter((item) => {
    if (filterAction !== 'All' && item.action !== filterAction) return false;
    if (
      searchTerm &&
      !item.txHash.toLowerCase().includes(searchTerm.toLowerCase()) &&
      !item.userAddress.toLowerCase().includes(searchTerm.toLowerCase()) &&
      !item.poolId.toLowerCase().includes(searchTerm.toLowerCase())
    ) {
      return false;
    }
    return true;
  });

  return (
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      
      {/* Section Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">
        <div>
          <div className="flex items-center space-x-2">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
              Verifiable Proof of User Wallet Interactions
            </h2>
            <span className="text-[10px] uppercase font-bold tracking-widest px-2.5 py-1 rounded-full bg-primary/10 text-primary border border-primary/20">
              12 On-Chain Proofs
            </span>
          </div>
          <p className="text-sm text-slate-400 mt-1">
            Real testnet transaction hashes, Ed25519 signer accounts, and block ledger heights verifiable on StellarExpert explorer.
          </p>
        </div>
      </div>

      {/* Summary Verification Banner */}
      <div className="p-6 rounded-3xl glass-panel border border-surface-border mb-8 grid grid-cols-1 sm:grid-cols-3 gap-6">
        <div className="flex items-center space-x-3">
          <div className="w-12 h-12 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
            <ShieldCheck className="w-6 h-6" />
          </div>
          <div>
            <div className="text-xs text-slate-400 uppercase font-bold">On-Chain Veracity</div>
            <div className="text-base font-bold text-white">100% Testnet Signed</div>
          </div>
        </div>

        <div className="flex items-center space-x-3">
          <div className="w-12 h-12 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center text-primary">
            <Activity className="w-6 h-6" />
          </div>
          <div>
            <div className="text-xs text-slate-400 uppercase font-bold">Total Verified Proofs</div>
            <div className="text-base font-bold text-white font-mono">{allProofs.length} Transactions</div>
          </div>
        </div>

        <div className="flex items-center space-x-3">
          <div className="w-12 h-12 rounded-2xl bg-stellar-cyan/10 border border-stellar-cyan/20 flex items-center justify-center text-stellar-cyan">
            <Layers className="w-6 h-6" />
          </div>
          <div>
            <div className="text-xs text-slate-400 uppercase font-bold">Explorer Verification</div>
            <a
              href={`${STELLAR_CONFIG.explorerBaseUrl}/contract/${STELLAR_CONFIG.contractId}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs font-bold text-primary hover:underline flex items-center space-x-1"
            >
              <span>Inspect Contract State</span>
              <ExternalLink className="w-3 h-3" />
            </a>
          </div>
        </div>
      </div>

      {/* Search & Action Filters */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
        <div className="relative flex-1 max-w-md">
          <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search by Tx Hash, Public Key, or Pool ID..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 rounded-xl bg-surface border border-surface-border text-xs text-white placeholder:text-slate-500 focus:outline-none focus:border-primary/40 font-mono min-touch-target"
          />
        </div>

        <div className="flex flex-wrap items-center gap-1.5 p-1 rounded-xl bg-surface border border-surface-border">
          {['All', 'Deposit', 'Auto-Compound', 'Withdraw', 'Emergency-Exit'].map((act) => (
            <button
              key={act}
              onClick={() => setFilterAction(act)}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                filterAction === act
                  ? 'bg-surface-light text-primary border border-primary/20 shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {act}
            </button>
          ))}
        </div>
      </div>

      {/* Proof Table */}
      <div className="glass-panel rounded-3xl border border-surface-border overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-surface-light/80 uppercase font-bold text-slate-400 tracking-wider border-b border-surface-border">
              <tr>
                <th className="py-3.5 px-5">Action</th>
                <th className="py-3.5 px-5">User Address</th>
                <th className="py-3.5 px-5">Amount / Type</th>
                <th className="py-3.5 px-5">Pool ID</th>
                <th className="py-3.5 px-5">Ledger</th>
                <th className="py-3.5 px-5">Timestamp (UTC)</th>
                <th className="py-3.5 px-5 text-right">Verification</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-surface-border font-medium">
              {filteredProofs.map((proof) => (
                <tr key={proof.id} className="hover:bg-surface-light/40 transition-colors">
                  
                  {/* Action Badge */}
                  <td className="py-3.5 px-5">
                    <span
                      className={`inline-flex items-center space-x-1.5 px-2.5 py-1 rounded-full font-bold text-[10px] uppercase border ${
                        proof.action === 'Deposit'
                          ? 'bg-primary/10 text-primary border-primary/20'
                          : proof.action === 'Auto-Compound'
                          ? 'bg-stellar-blue/10 text-stellar-cyan border-stellar-blue/20'
                          : proof.action === 'Withdraw'
                          ? 'bg-stellar-purple/10 text-stellar-purple border-stellar-purple/20'
                          : 'bg-red-500/10 text-red-400 border-red-500/20'
                      }`}
                    >
                      {proof.action === 'Deposit' && <ArrowDownRight className="w-3 h-3" />}
                      {proof.action === 'Withdraw' && <ArrowUpRight className="w-3 h-3" />}
                      {proof.action === 'Auto-Compound' && <Sparkles className="w-3 h-3" />}
                      <span>{proof.action}</span>
                    </span>
                  </td>

                  {/* Public Key */}
                  <td className="py-3.5 px-5 font-mono text-slate-300">
                    <span title={proof.userAddress}>
                      {proof.userAddress.substring(0, 4)}...{proof.userAddress.substring(proof.userAddress.length - 4)}
                    </span>
                  </td>

                  {/* Amount */}
                  <td className="py-3.5 px-5 font-mono font-bold text-white">
                    {proof.amount}
                  </td>

                  {/* Pool ID */}
                  <td className="py-3.5 px-5 font-mono text-slate-400">
                    {proof.poolId}
                  </td>

                  {/* Ledger */}
                  <td className="py-3.5 px-5 font-mono text-slate-400">
                    #{proof.ledger}
                  </td>

                  {/* Timestamp */}
                  <td className="py-3.5 px-5 text-slate-400 font-mono">
                    {proof.timestamp}
                  </td>

                  {/* Link to StellarExpert */}
                  <td className="py-3.5 px-5 text-right">
                    <a
                      href={proof.explorerUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center space-x-1 px-3 py-1.5 rounded-lg bg-surface border border-surface-border hover:border-primary/40 text-primary font-mono font-bold hover:bg-surface-light transition-all min-touch-target"
                    >
                      <span>{proof.txHash.substring(0, 6)}...</span>
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </td>

                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </section>
  );
};
